name: Rust Post-Submit CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: sudo apt install libavutil-dev libavformat-dev libavfilter-dev libavformat-dev libclang-dev libavdevice-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
